
title: Online CV
url: 'https://denisbernardo.com'
baseurl: 'https://denisbernardo.com/' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Denis Bernardo
tagline: Software Developer
pic: perfil2.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: oi@denisbernardo.com
phone: +55 43 9 9983 2798
website:  #do not add http://
linkedin: denis-bernardo-3654a984
github: denis-bernardo


# Tracker
analytics: UA-80644809-1
#Update all the sections by editing the files inside _includes folder.
